services:
  pot:
    build: .
    container_name: pot_container
    environment:
      FLAG: rctf{0n3_4g3n7_70_rul3_7h3m_4ll_776974686c6f766566726f6d4665444558}
    ports:
      - "6432:6432"
    restart: always